import {useState} from 'react';
import {Upload,LoaderCircle} from 'lucide-react';
import {api,Field} from './main.jsx';

const fields=[['phone_primary','Số điện thoại chính'],['phone_secondary','Số Zalo / LINE'],['email_contact','Email liên hệ'],['email_notifications','Email nhận thông báo'],['hero_title','Tiêu đề banner'],['hero_accent','Dòng chữ đỏ banner'],['hero_description','Mô tả banner'],['hero_caption','Chú thích trên ảnh'],['about_title','Tiêu đề giới thiệu'],['about_text_1','Giới thiệu — đoạn 1'],['about_text_2','Giới thiệu — đoạn 2'],['amenities_title','Tiêu đề tiện ích'],['amenities_description','Mô tả tiện ích'],['amenity_1_title','Dịch vụ 1 — tiêu đề'],['amenity_1_text','Dịch vụ 1 — nội dung'],['amenity_2_title','Dịch vụ 2 — tiêu đề'],['amenity_2_text','Dịch vụ 2 — nội dung'],['amenity_3_title','Dịch vụ 3 — tiêu đề'],['amenity_3_text','Dịch vụ 3 — nội dung'],['amenity_4_title','Dịch vụ 4 — tiêu đề'],['amenity_4_text','Dịch vụ 4 — nội dung'],['facebook_url','Facebook'],['zalo_url','Zalo'],['youtube_url','YouTube']];

export default function AdminSettings({catalog,setCatalog,onUpdate,fail,setNotice}){
 const [busy,setBusy]=useState(false),[uploading,setUploading]=useState(false);const settings=catalog.settings||{};
 const set=(key,value)=>setCatalog(current=>({...current,settings:{...current.settings,[key]:value}}));
 const setLocation=(index,key,value)=>setCatalog(current=>({...current,locations:current.locations.map((row,i)=>i===index?{...row,[key]:value}:row)}));
 async function uploadLogo(e){const file=e.target.files?.[0];e.target.value='';if(!file)return;setUploading(true);try{const body=new FormData();body.append('file',file);const media=await api('/api/admin/upload',{method:'POST',body});if(media.kind!=='image')throw new Error('Logo phải là tệp ảnh.');set('logo_url',media.url);setNotice('Đã tải logo. Nhấn Lưu thông tin website để áp dụng.');}catch(error){fail(error);}finally{setUploading(false);}}
 async function save(){setBusy(true);try{await Promise.all([api('/api/admin/settings',{method:'PUT',body:JSON.stringify({...settings,banner_interval:Number(settings.banner_interval||5)})}),api('/api/admin/locations',{method:'PUT',body:JSON.stringify(catalog.locations)})]);setNotice('Đã cập nhật thông tin website.');onUpdate();}catch(error){fail(error);}finally{setBusy(false);}}
 return <details className="editor settings-editor"><summary>Thông tin website — sửa không cần build lại</summary><div className="form-grid">{fields.map(([key,label])=><Field label={label} className={key.includes('text')||key.includes('description')?'full':''} key={key}>{key.includes('text')||key.includes('description')?<textarea rows={3} value={settings[key]||''} onChange={e=>set(key,e.target.value)}/>:<input type={key.includes('email')?'email':key.includes('url')?'url':'text'} value={settings[key]||''} onChange={e=>set(key,e.target.value)}/>}</Field>)}<Field label="Thời gian chuyển banner (giây)"><input type="number" min="2" max="60" value={settings.banner_interval||5} onChange={e=>set('banner_interval',Number(e.target.value))}/></Field><Field label="Đường dẫn logo"><input value={settings.logo_url||''} onChange={e=>set('logo_url',e.target.value)}/></Field></div><label className="upload-zone compact"><input type="file" accept="image/*" onChange={uploadLogo}/>{uploading?<LoaderCircle className="spin"/>:<Upload/>}<strong>Tải logo mới</strong></label><h3>Địa chỉ các cơ sở</h3>{catalog.locations.map((location,index)=><div className="location-setting" key={location.id}><input value={location.name} onChange={e=>setLocation(index,'name',e.target.value)}/><input value={location.address} onChange={e=>setLocation(index,'address',e.target.value)}/><textarea rows={2} value={location.description} onChange={e=>setLocation(index,'description',e.target.value)}/></div>)}<div className="editor-actions"><button className="button" disabled={busy||uploading} onClick={save}>{busy?'Đang lưu…':'Lưu thông tin website'}</button></div></details>;
}
