import React,{createContext,useContext,useEffect,useMemo,useState} from 'react';

const copy={
  'Giới thiệu':['About','RubyHouseについて'],'Tiện ích & dịch vụ':['Amenities & services','設備・サービス'],'Liên hệ':['Contact','お問い合わせ'],'Đặt lịch xem':['Book a viewing','内見を予約'],'Hoạt động từ 2019':['Established in 2019','2019年創業'],
  'QUẬN BA ĐÌNH, HÀ NỘI':['BA DINH, HANOI','ハノイ・バーディン区'],'Không gian sống mang tinh thần Nhật Bản':['Japanese-inspired living','日本のおもてなしを感じる住まい'],'TINH THẦN OMOTENASHI':['THE SPIRIT OF OMOTENASHI','おもてなしの心'],'RUBYHOUSE · SINCE 2019':['RUBYHOUSE · SINCE 2019','RUBYHOUSE · 2019年創業'],
  'Căn hộ đầy đủ nội thất, tiện nghi giữa lòng Hà Nội — luôn có RubyHouse đồng hành trong suốt thời gian bạn lưu trú.':['Comfortable, fully furnished apartments in the heart of Hanoi — with reliable RubyHouse support throughout your stay.','ハノイ中心部の家具・設備付きアパートメント。ご滞在中はRubyHouseがいつでもサポートします。'],'Khám phá căn hộ':['View apartments','お部屋を見る'],'Đặt lịch xem phòng':['Book a viewing','内見を予約'],'Địa điểm tại Ba Đình':['Locations in Ba Dinh','バーディン区の拠点'],'Năm bắt đầu hoạt động':['Established','創業年'],'Hỗ trợ khách thuê':['Guest support','入居者サポート'],
  '3 cơ sở tại Ba Đình':['3 locations in Ba Dinh','バーディン区に3拠点'],'Dọn phòng 3 lần/tuần':['Housekeeping 3 times/week','週3回の清掃'],'Lễ tân & an ninh 24/7':['24/7 reception & security','24時間受付・セキュリティ'],'VỀ RUBYHOUSE':['ABOUT RUBYHOUSE','RUBYHOUSEについて'],'Chỗ ở đáng tin cậy cho chuyên gia quốc tế tại Hà Nội.':['A trusted home for international professionals in Hanoi.','ハノイで働く海外の方に、信頼できる住まいを。'],
  'Đáng tin cậy':['Trustworthy','信頼'],'Chuyên nghiệp':['Professional','プロフェッショナル'],'Ấm áp':['Warm','温かさ'],'Quốc tế':['International','国際対応'],'Am hiểu địa phương':['Local expertise','地域への理解'],'Chọn nơi bạn thuộc về':['Choose where you belong','あなたに合う住まいを'],'Ba điểm dừng chân, cùng sự tận tâm đặc trưng của Ruby House.':['Three locations, one consistent standard of RubyHouse care.','3つの拠点で、変わらないRubyHouseのおもてなしを。'],
  'BỘ SƯU TẬP CĂN HỘ':['APARTMENTS','アパートメント'],'Không gian cho nhịp sống của bạn':['A home that fits your life','暮らしに合う住まい'],'Từ studio tinh gọn đến căn hộ hai phòng ngủ rộng rãi.':['From efficient studios to spacious two-bedroom homes.','機能的なスタジオから広々とした2ベッドルームまで。'],'Tất cả địa điểm':['All locations','すべての拠点'],'Còn trống':['Available','空室'],'Đang cho thuê':['Occupied','入居中'],'Khám phá phòng':['View room','お部屋を見る'],'phòng ngủ':['bedroom','ベッドルーム'],'Liên hệ báo giá':['Contact for price','料金を問い合わせ'],
  'CHĂM CHÚT TỪ NHỮNG ĐIỀU NHỎ NHẤT':['CARE IN EVERY DETAIL','細部まで心を込めて'],'Bạn tận hưởng.':['Enjoy your stay.','快適な毎日を。'],'Chúng tôi chăm lo.':['We take care of the rest.','私たちが支えます。'],'Tìm hiểu cùng Ruby House':['Talk to RubyHouse','RubyHouseに相談'],'Phục vụ bằng cả sự chân thành':['Service from the heart','心を込めたおもてなし'],'Kết nối không gián đoạn':['Stay connected','快適な通信環境'],'Chăm sóc không gian sống':['A well-cared-for home','快適な住環境'],'Tiện nghi như ở nhà':['Comforts of home','自宅のような設備'],'Sống khỏe mỗi ngày':['Support every day','毎日の安心'],
  'GIÁ THUÊ THÁNG':['MONTHLY RENT','月額賃料'],'GIÁ ƯU ĐÃI THAM KHẢO':['PROMOTIONAL RATE','キャンペーン料金'],'GIÁ THUÊ NGÀY':['DAILY RATE','日額料金'],'Giá tham khảo, chưa gồm VAT 10%. Liên hệ để nhận báo giá theo thời điểm.':['Reference rates exclude 10% VAT. Contact us for the current quotation.','表示料金は参考価格で、VAT 10%は含まれていません。最新料金はお問い合わせください。'],'Xem ảnh':['View photos','写真を見る'],'Không gian dành cho bạn':['A space for you','あなたのための空間'],'Tiện nghi căn hộ':['Apartment amenities','室内設備'],'Căn hộ dịch vụ':['Serviced apartment','サービスアパートメント'],'TÌM HIỂU THÊM VỀ CĂN HỘ':['LEARN MORE','詳しく見る'],'Hẹn gặp bạn tại':['See you at','お待ちしています'],'Liên hệ để nhận báo giá và kiểm tra tình trạng phòng.':['Contact us for pricing and current availability.','料金と空室状況はお問い合わせください。'],'Hỗ trợ xem phòng qua video call':['Video viewing available','ビデオ内見対応'],'Video giới thiệu':['Introduction video','紹介動画'],
  'CHÚNG TÔI MONG ĐƯỢC ĐÓN BẠN':['WE LOOK FORWARD TO WELCOMING YOU','皆さまをお待ちしています'],'Ngôi nhà tiếp theo của bạn,':['Your next home','次の住まいは'],'bắt đầu từ một cuộc hẹn.':['starts with a viewing.','内見から始まります。'],'Xem phòng trực tiếp hoặc video call cùng đội ngũ Ruby House.':['View in person or by video call with the RubyHouse team.','現地またはビデオ通話で内見できます。'],'Đặt lịch xem căn hộ':['Book an apartment viewing','内見を予約'],
  'Hệ thống Ruby House':['RubyHouse locations','RubyHouseの拠点'],'Luôn sẵn lòng hỗ trợ':['Always here to help','いつでもサポート'],'Quản trị':['Admin','管理'],'Trang chủ / Địa điểm':['Home / Location','ホーム / 拠点'],'Đặt lịch xem tại đây':['Book a viewing here','この拠点を内見'],'Xem bản đồ':['View map','地図を見る'],'KHÁM PHÁ CĂN HỘ':['EXPLORE APARTMENTS','お部屋を見る'],'Loại phòng':['Room type','部屋タイプ'],'Tất cả loại phòng':['All room types','すべてのタイプ'],'Chưa có căn hộ phù hợp':['No matching apartments','該当するお部屋はありません'],'Xem tất cả phòng':['View all rooms','すべて見る']
};

Object.assign(copy,{
  'full furniture':['fully furnished','家具付き'],'city view':['city view','シティビュー'],'front side':['front-facing','正面向き'],'balcony':['balcony','バルコニー'],'Bedroom':['Bedroom','ベッドルーム'],'Tolet':['toilet','トイレ'],'WC':['bathroom','バスルーム'],'None':['None','なし'],'available':['available','空室'],'occupied':['occupied','入居中'],
  'Đối diện Đại sứ quán Nhật Bản, gần Lotte Center và Vinhomes Metropolis.':['Opposite the Embassy of Japan, near Lotte Center and Vinhomes Metropolis.','日本大使館の向かい、ロッテセンターとビンホームズ・メトロポリスの近く。'],'Không gian sống yên tĩnh giữa trung tâm, thuận tiện làm việc và di chuyển.':['Quiet living in the city center, convenient for work and travel.','都心にありながら静かで、通勤や移動にも便利。'],'Gần phố ẩm thực Nhật Bản Linh Lang và Kim Mã, tiện nghi cho cuộc sống mỗi ngày.':['Near the Japanese dining streets of Linh Lang and Kim Ma, convenient for everyday life.','リンラン・キンマーの日本食街に近く、日々の生活に便利。'],
  'RUBY HOUSE COLLECTION':['RUBYHOUSE COLLECTION','RUBYHOUSE コレクション'],'Sống thư thái, ở trọn vẹn.':['Comfortable living, complete peace of mind.','心地よく、安心できる暮らし。'],'03 ĐỊA ĐIỂM · MỘT CHUẨN MỰC SỐNG':['3 LOCATIONS · ONE STANDARD','3拠点・ひとつの品質'],'Trụ sở chính':['Main location','本店'],'loại căn hộ':['apartment types','部屋タイプ'],'Xem căn hộ':['View apartments','お部屋を見る'],
  'Một căn hộ đầy đủ tiện nghi cùng đội ngũ hỗ trợ thực sự trong suốt thời gian lưu trú — không chỉ là một giao dịch cho thuê.':['A fully furnished apartment with genuine support throughout your stay — not merely a rental transaction.','家具・設備の整った住まいと、ご滞在中のきめ細かなサポートをご提供します。'],'Wi-Fi tốc độ cao cùng truyền hình cáp Việt Nam, quốc tế và 79 kênh Nhật Bản.':['High-speed Wi-Fi with Vietnamese, international and 79 Japanese TV channels.','高速Wi-Fi、ベトナム・海外・日本の79チャンネルをご用意。'],'Dọn phòng 3 lần/tuần, thay chăn ga và bảo trì định kỳ.':['Housekeeping three times a week, linen changes and regular maintenance.','週3回の清掃、リネン交換、定期メンテナンス。'],'Bếp đầy đủ thiết bị, máy giặt và máy sấy riêng, điều hòa cùng nước nóng trung tâm.':['Fully equipped kitchen, private washer and dryer, air conditioning and central hot water.','設備の整ったキッチン、専用洗濯乾燥機、エアコン、集中給湯。'],'Lễ tân và bảo vệ 24/7, hỗ trợ thủ tục tạm trú cho khách nước ngoài.':['24/7 reception and security, with temporary-residence support for international guests.','24時間受付・警備、外国人向け一時滞在登録をサポート。'],
  'RubyHouse được vận hành bởi Công ty TNHH Ruby Holding, bắt đầu hoạt động từ năm 2019 tại Ba Đình — khu vực tập trung nhiều văn phòng đại diện, đại sứ quán và cộng đồng chuyên gia nước ngoài.':['Operated by Ruby Holding Co., Ltd., RubyHouse was established in 2019 in Ba Dinh — home to representative offices, embassies and a large international professional community.','RubyHouseはRuby Holding Co., Ltd.が運営し、2019年にバーディン区で開業しました。周辺には大使館や海外企業の駐在員事務所が多くあります。'],'Từ 3 cơ sở Vạn Phúc, Liễu Giai và Phan Kế Bính, chúng tôi cung cấp căn hộ Studio, 1 và 2 phòng ngủ cho cả khách thuê dài hạn và khách công tác ngắn ngày. RubyHouse lựa chọn phân khúc cao cấp vừa phải: chất lượng đáng tin cậy, dịch vụ chuyên nghiệp và mức giá hợp lý.':['Across Van Phuc, Lieu Giai and Phan Ke Binh, we offer studios, one- and two-bedroom apartments for long-term residents and short business stays. RubyHouse delivers reliable quality and professional service at a sensible premium.','ヴァンフック、リエウザイ、ファンケビンの3拠点で、長期滞在や出張向けのスタジオ、1～2ベッドルームをご提供。信頼できる品質とプロのサービスを適正な価格でお届けします。'],
  'Không gian sống riêng tư với nội thất đầy đủ, khu vực bếp và góc làm việc. Vui lòng liên hệ Ruby House để được tư vấn thông tin và tình trạng phòng thực tế.':['A private, fully furnished home with a kitchen and workspace. Contact RubyHouse for current availability and details.','家具、キッチン、ワークスペースを備えたプライベートな住まいです。最新の空室状況はお問い合わせください。'],'Wi-Fi tốc độ cao':['High-speed Wi-Fi','高速Wi-Fi'],'Bếp đầy đủ tiện nghi':['Fully equipped kitchen','設備の整ったキッチン'],'Điều hòa 2 chiều':['Heating and air conditioning','冷暖房'],'Máy giặt':['Washing machine','洗濯機'],'Bồn tắm':['Bathtub','バスタブ'],'Dọn phòng':['Housekeeping','清掃サービス'],'Truyền hình cáp quốc tế và Nhật Bản':['International and Japanese cable TV','海外・日本語ケーブルテレビ'],'Máy giặt và máy sấy riêng':['Private washer and dryer','専用洗濯乾燥機'],'Nước nóng trung tâm':['Central hot water','集中給湯'],
  'phòng ngủ':['bedroom','ベッドルーム'],'Phòng ':['Room ','ルーム '],'USD/tháng':['USD/month','USD／月'],'VNĐ/ngày':['VND/day','VND／日'],'m²':['m²','m²'],'Ảnh ':['Photo ','写真 '],'Xem ảnh ·':['View photos ·','写真を見る ·'],'Ảnh trước':['Previous photo','前の写真'],'Ảnh tiếp theo':['Next photo','次の写真'],'Đóng thư viện':['Close gallery','ギャラリーを閉じる'],'Phóng to ảnh căn hộ':['Enlarge apartment photo','写真を拡大'],
  'Trang chủ / Địa điểm':['Home / Location','ホーム / 拠点'],'Ruby House ':['RubyHouse ','RubyHouse '],'Đặt lịch xem tại đây':['Book a viewing here','この拠点を内見'],'Căn hộ tại ':['Apartments at ','のお部屋'],'Chưa có căn hộ phù hợp':['No matching apartments','該当するお部屋はありません'],'Chọn loại phòng khác hoặc liên hệ để được tư vấn.':['Choose another room type or contact us for advice.','別のタイプを選ぶか、お問い合わせください。'],'Studio':['Studio','スタジオ'],'1 phòng ngủ':['1 bedroom','1ベッドルーム'],'2 phòng ngủ':['2 bedrooms','2ベッドルーム'],
  'RUBY HOUSE LUÔN SẴN LÒNG':['RUBYHOUSE IS HERE TO HELP','RUBYHOUSEがサポートします'],'Hãy đến và':['Come and','ぜひ'],'cảm nhận.':['experience it.','ご体感ください。'],'Để lại lời nhắn, chúng tôi sẽ liên hệ xác nhận lịch hẹn và tư vấn căn hộ phù hợp với bạn.':['Leave us a message and we will confirm your viewing and recommend a suitable apartment.','メッセージをお送りください。内見日時を確認し、ご希望に合うお部屋をご案内します。'],'HOTLINE / ZALO / LINE':['HOTLINE / ZALO / LINE','電話 / ZALO / LINE'],'MỘT CUỘC HẸN, MỘT KHỞI ĐẦU':['A VIEWING, A NEW BEGINNING','内見から始まる新しい暮らし'],'Đặt lịch xem căn hộ':['Book an apartment viewing','内見を予約'],'Họ và tên *':['Full name *','お名前 *'],'Tên của bạn':['Your name','お名前'],'Số điện thoại *':['Phone number *','電話番号 *'],'Email':['Email','メール'],'Địa điểm *':['Location *','拠点 *'],'Căn hộ quan tâm':['Apartment of interest','ご希望のお部屋'],'Tôi cần được tư vấn':['I need a recommendation','相談したい'],'Ngày dự kiến':['Preferred date','希望日'],'Hình thức xem phòng':['Viewing method','内見方法'],'Trực tiếp':['In person','現地'],'Video call':['Video call','ビデオ通話'],'Lời nhắn của bạn':['Your message','メッセージ'],'Thời gian thuận tiện, nhu cầu thuê hoặc yêu cầu đặc biệt…':['Preferred time, rental needs or special requests…','ご希望の時間、期間、その他のご要望…'],'Thông tin của bạn chỉ được dùng để tư vấn và xác nhận lịch hẹn.':['Your information is used only to advise you and confirm the viewing.','個人情報はご案内と内見確認のみに使用します。'],'Gửi yêu cầu đặt lịch':['Send viewing request','内見を申し込む'],'Đang gửi…':['Sending…','送信中…'],'Hẹn gặp bạn tại Ruby House!':['See you at RubyHouse!','RubyHouseでお待ちしています！'],'Yêu cầu đã được lưu. Đội ngũ Ruby House sẽ liên hệ để xác nhận lịch xem phòng.':['Your request has been saved. The RubyHouse team will contact you to confirm.','お申し込みを受け付けました。担当者より確認のご連絡をいたします。'],'Mã yêu cầu:':['Request ID:','受付番号：'],'Về trang chủ':['Back to home','ホームへ戻る'],
  'Không tìm thấy trang':['Page not found','ページが見つかりません'],'Trang hoặc căn hộ này hiện không có trên website.':['This page or apartment is not currently available on the website.','このページまたはお部屋は現在掲載されていません。'],'Đang chuẩn bị không gian của bạn…':['Preparing your space…','お部屋を準備しています…'],'Thử lại':['Try again','再試行'],'Đang mở quản trị…':['Opening admin…','管理画面を開いています…']
});

Object.assign(copy,{
  'Không kết nối được máy chủ. Vui lòng thử lại.':['Cannot connect to the server. Please try again.','サーバーに接続できません。もう一度お試しください。'],
  'Yêu cầu chưa hoàn tất. Vui lòng thử lại.':['The request could not be completed. Please try again.','処理を完了できませんでした。もう一度お試しください。'],
  'Ruby House — trang chủ':['RubyHouse — home','RubyHouse — ホーム'],'Hình ảnh đang được cập nhật':['Images are being updated','写真を準備中です'],'Căn hộ Ruby House':['RubyHouse apartment','RubyHouseのお部屋'],'Không gian Ruby House':['RubyHouse interior','RubyHouseの室内'],
  'Điều hướng chính':['Main navigation','メインナビゲーション'],'Đóng menu':['Close menu','メニューを閉じる'],'Mở menu':['Open menu','メニューを開く'],'Ba Đình, Hà Nội':['Ba Dinh, Hanoi','ハノイ・バーディン区'],
  'Căn hộ tiện nghi, dịch vụ đáng tin cậy.':['Comfortable apartments, dependable service.','快適な住まいと信頼できるサービス。'],'CÔNG TY TNHH RUBY HOLDING · SINCE 2019':['RUBY HOLDING CO., LTD. · SINCE 2019','RUBY HOLDING CO., LTD.・2019年創業'],'BA ĐÌNH · HÀ NỘI · VIỆT NAM':['BA DINH · HANOI · VIETNAM','バーディン・ハノイ・ベトナム'],'All rights reserved.':['All rights reserved.','無断転載を禁じます。'],
  'Your trusted home away from home.':['Your trusted home away from home.','信頼できる、もうひとつの我が家。'],'Your trusted home':['Your trusted home','信頼できる'],'away from home.':['away from home.','もうひとつの我が家。'],'YOUR HOME AWAY FROM HOME':['YOUR HOME AWAY FROM HOME','もうひとつの我が家'],'RUBY HOUSE COLLECTION':['RUBYHOUSE COLLECTION','RUBYHOUSE コレクション'],
  'Phân trang':['Pagination','ページ切り替え'],'← Trước':['← Previous','← 前へ'],'Sau →':['Next →','次へ →'],'Lọc theo địa điểm':['Filter by location','拠点で絞り込む'],'Danh sách căn hộ đang được cập nhật. Vui lòng liên hệ để được tư vấn.':['The apartment list is being updated. Please contact us for assistance.','お部屋情報を更新中です。詳しくはお問い合わせください。'],
  'RUBY HOUSE · CƠ SỞ ':['RUBYHOUSE · LOCATION ','RUBYHOUSE・拠点'],'Căn hộ còn trống':['Available apartment','空室のお部屋'],'Thư viện ảnh căn hộ':['Apartment photo gallery','お部屋の写真ギャラリー'],'Xem ảnh ':['View photo ','写真を見る '],
  'Số 1–3, ngõ 1 Vạn Phúc, Ba Đình, Hà Nội':['1–3, Alley 1 Van Phuc, Ba Dinh, Hanoi','ハノイ市バーディン区ヴァンフック1通り1–3番地'],'Số 13, ngõ 19 Liễu Giai, Ba Đình, Hà Nội':['13, Alley 19 Lieu Giai, Ba Dinh, Hanoi','ハノイ市バーディン区リエウザイ19通り13番地'],'Số 12, ngõ 35 Phan Kế Bính, Ba Đình, Hà Nội':['12, Alley 35 Phan Ke Binh, Ba Dinh, Hanoi','ハノイ市バーディン区ファンケビン35通り12番地'],
  'Trụ sở chính':['Main location','本店'],'loại căn hộ':['apartment types','部屋タイプ'],'Xem căn hộ':['View apartments','お部屋を見る']
  ,'cityview':['city view','シティビュー']
});

const LanguageContext=createContext({lang:'vi',setLang:()=>{}});
const langs=['vi','en','ja'];
function detected(){const saved=localStorage.getItem('ruby_language');if(langs.includes(saved))return saved;const code=(navigator.languages?.[0]||navigator.language||'vi').toLowerCase();return code.startsWith('ja')?'ja':code.startsWith('en')?'en':'vi';}

export function LanguageProvider({children}){const [lang,setLanguage]=useState(detected);const setLang=value=>{localStorage.setItem('ruby_language',value);setLanguage(value);};useEffect(()=>{document.documentElement.lang=lang;},[lang]);return <LanguageContext.Provider value={{lang,setLang}}>{children}<Translator lang={lang}/></LanguageContext.Provider>}
export const useLanguage=()=>useContext(LanguageContext);
export function LanguageSwitcher(){const {lang,setLang}=useLanguage();return <div className="language-switcher" aria-label="Language">{[['vi','VI'],['en','EN'],['ja','日本語']].map(([code,label])=><button type="button" className={lang===code?'active':''} onClick={()=>setLang(code)} key={code}>{label}</button>)}</div>}

function Translator({lang}){const entries=useMemo(()=>Object.entries(copy).sort((a,b)=>b[0].length-a[0].length),[]);useEffect(()=>{if(location.pathname.startsWith('/quan-tri'))return;const localize=text=>{let value=text;for(const [vi,[en,ja]] of entries){const target=lang==='vi'?vi:lang==='en'?en:ja;for(const source of [vi,en,ja])if(source&&value.includes(source)){value=value.split(source).join(target);break}}return value};const translate=root=>{if(!root)return;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const node of nodes){if(['SCRIPT','STYLE'].includes(node.parentElement?.tagName))continue;node.nodeValue=node.parentElement?.matches('.hero-copy h1 em')?(lang==='ja'?'もうひとつの我が家。':'AWAY FROM HOME.'):localize(node.nodeValue)}for(const element of root.querySelectorAll?.('[placeholder],[aria-label]')||[]){for(const attr of ['placeholder','aria-label'])if(element.hasAttribute(attr))element.setAttribute(attr,localize(element.getAttribute(attr)))}};translate(document.body);const observer=new MutationObserver(records=>records.forEach(record=>record.addedNodes.forEach(node=>translate(node.nodeType===1?node:node.parentElement))));observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect();},[lang,entries]);return null;}
